 
development:
  adapter: mysql2
  encoding: utf8
  database: db/development
  pool: 5
  username: root
  password: secretpassword
test:
  adapter: mysql2
  encoding: utf8
  database: db/test
  pool: 5
  username: root
  password: secretpassword
production:
  adapter: mysql2
  encoding: utf8
  database: db/production
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  username: root
  password: secretpassword
